/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_menu;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JOptionPane;
import stationerypro.StationeryPro;

/**
 *
 * @author anonim
 */
public class Loading_Form extends javax.swing.JFrame {

    /**
     * Creates new form Loading_Form
     */
    public Loading_Form() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        seticon();
        setTitle("Loading - Stationery Pro");
    }
        private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/assets/Taskbar_Icon.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Loading_Value = new javax.swing.JLabel();
        Loading_Label = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Loading_Value.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Loading_Value.setForeground(new java.awt.Color(240, 224, 96));
        Loading_Value.setText("0%");
        getContentPane().add(Loading_Value, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        Loading_Label.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Loading_Label.setForeground(new java.awt.Color(240, 224, 96));
        Loading_Label.setText("Loading...");
        getContentPane().add(Loading_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        ProgressBar.setForeground(new java.awt.Color(240, 224, 96));
        getContentPane().add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 320, 10));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Loading_Screen_Yellow.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Loading_Form lf = new Loading_Form();
        lf.setVisible(true);
        
        try {
            for (int i =0; i<=100; i++) {
                Thread.sleep(40);
                lf.Loading_Value.setText(i + "%");
                
                if(i==10){
                    lf.Loading_Label.setText("Turning On Modules...");
                }
                if(i==20){
                    lf.Loading_Label.setText("Loading Modules...");
                }
                if(i==50){
                    lf.Loading_Label.setText("Connecting To Modules...");
                }
                if(i==70){
                    lf.Loading_Label.setText("Connection Successful...");
                }
                if(i==80){
                    lf.Loading_Label.setText("Launching Application...");
                }
                if(i==100){
                    lf.Loading_Label.setText("Ready To Go...");
//                    Thread.sleep(1000);
                    lf.dispose();
                    new Login_Form().setVisible(true);
                }
                lf.ProgressBar.setValue(i);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Loading_Label;
    private javax.swing.JLabel Loading_Value;
    private javax.swing.JProgressBar ProgressBar;
    // End of variables declaration//GEN-END:variables
}
